export type PageContentTemplate = {
  section: string;
  label: string;
  title?: string;
  content?: string;
  imageUrl?: string;
  metadata?: Record<string, unknown>;
};

export const PAGE_CONTENT_TEMPLATES: PageContentTemplate[] = [
  {
    section: "layout.navbar",
    label: "Navbar",
    title: "Ana Navigasyon",
    content: "Üst bar, menü ve arama alanı ayarları",
    metadata: {
      topBarPhone: "444 9 184",
      topBarEmail: "info@vaden.com.tr",
      logoTitle: "VADEN",
      logoSubtitle: "ORIGINAL",
      lightModeTitle: "Light Mode",
      darkModeTitle: "Dark Mode",
      searchPlaceholderTr: "OEM Kodu Ara...",
      searchPlaceholderEn: "Search OEM Code...",
      navItems: [
        {
          labelTr: "Kurumsal",
          labelEn: "Corporate",
          href: "/kurumsal",
          children: [
            { labelTr: "Hakkımızda", labelEn: "About", href: "/kurumsal?tab=about" },
            { labelTr: "Tarihçe", labelEn: "History", href: "/kurumsal?tab=history" },
            { labelTr: "Yönetim Kurulu", labelEn: "Board", href: "/kurumsal?tab=board" },
            {
              labelTr: "Sertifikalar",
              labelEn: "Certifications",
              href: "/kurumsal?tab=certifications",
            },
          ],
        },
        {
          labelTr: "Ürünler",
          labelEn: "Products",
          href: "/#urunler",
          children: [
            {
              labelTr: "Hava İşleme Ünitesi (E-APU)",
              labelEn: "Air Handling Unit (E-APU)",
              href: "/#urunler",
            },
            {
              labelTr: "Hava Fren Kompresörleri",
              labelEn: "Air Brake Compressors",
              href: "/#urunler",
            },
            {
              labelTr: "Hava Fren Sistemleri",
              labelEn: "Air Brake Systems",
              href: "/#urunler",
            },
            {
              labelTr: "Şanzıman, Solenoid Valfler",
              labelEn: "Transmission, Solenoid Valves",
              href: "/#urunler",
            },
            {
              labelTr: "Motor, Egzoz Fren Valfleri",
              labelEn: "Engine, Exhaust Brake Valves",
              href: "/#urunler",
            },
            {
              labelTr: "Motor, Volan Muhafazası",
              labelEn: "Engine, Flywheel Housing",
              href: "/#urunler",
            },
          ],
        },
        {
          labelTr: "Üretim",
          labelEn: "Manufacturing",
          href: "/#uretim",
          children: [
            {
              labelTr: "Konya Üretim Tesisi",
              labelEn: "Konya Manufacturing Facility",
              href: "/#uretim",
            },
            {
              labelTr: "Bursa Kauçuk Üretim Tesisi",
              labelEn: "Bursa Rubber Manufacturing Facility",
              href: "/#uretim",
            },
          ],
        },
        { labelTr: "Ar-Ge", labelEn: "R&D", href: "/#arge" },
        { labelTr: "Sürdürülebilirlik", labelEn: "Sustainability", href: "/#global" },
        { labelTr: "Haberler", labelEn: "News", href: "/#haberler" },
        { labelTr: "İletişim", labelEn: "Contact", href: "/#iletisim" },
      ],
    },
  },
  {
    section: "layout.footer",
    label: "Footer",
    title: "Alt Bilgi Alanı",
    content: "Footer metinleri, linkleri ve iletişim alanı",
    metadata: {
      logoTitle: "VADEN",
      logoSubtitle: "ORIGINAL",
      sectionProductsTitle: "Ürünler",
      sectionCorporateTitle: "Kurumsal",
      sectionContactTitle: "İletişim",
      brandDescription:
        "56 yıllık deneyimle hava fren sistemleri ve otomotiv yedek parçaları üretiminde küresel lider.",
      socialLinks: [
        { icon: "facebook", href: "https://www.facebook.com/vadenoriginal" },
        { icon: "instagram", href: "https://www.instagram.com/vadenoriginal/" },
        { icon: "twitter", href: "https://x.com/@vadenoriginal" },
        { icon: "linkedin", href: "https://www.linkedin.com/company/vadenoriginal/" },
        { icon: "youtube", href: "https://www.youtube.com/@vadenoriginal" },
      ],
      productLinks: [
        { label: "Hava İşleme Ünitesi (E-APU)", href: "/#urunler" },
        { label: "Hava Fren Kompresörleri", href: "/#urunler" },
        { label: "Hava Fren Sistemleri", href: "/#urunler" },
        { label: "Şanzıman, Solenoid Valfler", href: "/#urunler" },
        { label: "Motor, Egzoz Fren Valfleri", href: "/#urunler" },
        { label: "Hava Fren Sistemleri, Valfler", href: "/#urunler" },
        { label: "Motor, Volan Muhafazası", href: "/#urunler" },
      ],
      corporateLinks: [
        { label: "Hakkımızda", href: "/kurumsal?tab=about" },
        { label: "Tarihçe", href: "/kurumsal?tab=history" },
        { label: "Üretim Tesisleri", href: "/#uretim" },
        { label: "Ar-Ge", href: "/#arge" },
        { label: "Sürdürülebilirlik", href: "/#global" },
        { label: "Ödüller & Başarılar", href: "/#oduller" },
        { label: "Kariyer", href: "/kariyer" },
        { label: "Haberler", href: "/#haberler" },
      ],
      addressLines: ["Vaden Otomotiv San. Tic. A.Ş.", "Konya, Türkiye"],
      phone: "444 9 184",
      email: "info@vaden.com.tr",
      newsletterTitle: "E-Bülten Aboneliği",
      newsletterPlaceholder: "E-posta adresiniz",
      newsletterButton: "ABONE OL",
      copyrightText: "© Vaden Otomotiv San. Tic. A.Ş. Tüm hakları saklıdır / 2026",
      policyLinks: [
        { label: "Gizlilik Politikası", href: "/politikalar?tab=privacy" },
        { label: "KVKK", href: "/politikalar?tab=kvkk" },
        { label: "Çerez Politikası", href: "/politikalar?tab=cookies" },
      ],
    },
  },
  {
    section: "home.hero",
    label: "Home Hero",
    title: "Ana Slider",
    content: "Ana sayfa hero slider metinleri",
    metadata: {
      secondaryCtaText: "Hakkımızda",
      secondaryCtaHref: "#hakkimizda",
      slides: [
        {
          id: 1,
          image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1920&q=80",
          tag: "YENİ ÜRÜN",
          title: "Hava İşleme Ünitesi",
          subtitle: "(E-APU)",
          description: "Güvenli ve Verimli Hava Yönetimi",
          cta: "Ürünü İncele",
          ctaHref: "#urunler",
        },
        {
          id: 2,
          image: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1920&q=80",
          tag: "ÖNCÜ TEKNOLOJİ",
          title: "Hava Fren",
          subtitle: "Kompresörleri",
          description:
            "Gelişmiş teknolojiyle donatılmış, güvenilir ve yüksek performanslı hava fren kompresörlerimiz.",
          cta: "Keşfet",
          ctaHref: "#urunler",
        },
        {
          id: 3,
          image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=1920&q=80",
          tag: "KALİTE STANDARDI",
          title: "Hava Fren",
          subtitle: "Sistemleri",
          description: "Temiz Hava, Üstün Kalite Standartları!",
          cta: "Ürün Kataloğu",
          ctaHref: "#urunler",
        },
      ],
    },
  },
  {
    section: "home.oemSearch",
    label: "Home OEM Search",
    title: "OEM Arama",
    content: "OEM arama modülü metinleri",
    metadata: {
      tag: "Hızlı Arama",
      title: "OEM Kodu ile Ara",
      placeholder: "OEM kodu veya ürün adı girin...",
      buttonText: "ARA",
      autocompleteOemLabel: "OEM Kodları",
      autocompleteProductLabel: "Ürünler",
      autocompleteCategoryLabel: "Kategoriler",
      samplePrefix: "Örnek:",
      sampleOne: "K013872",
      sampleTwo: "Kompresör",
    },
  },
  {
    section: "home.newsTicker",
    label: "Home News Ticker",
    title: "Duyuru Şeridi",
    content: "Haber ticker yardımcı metinleri",
    metadata: {
      labelText: "DUYURULAR",
      readMoreText: "Devamını Oku",
    },
  },
  {
    section: "home.products",
    label: "Home Products Header",
    title: "Ürün Kategorileri",
    content: "Ürünlerimiz",
    metadata: {
      label: "Ürün Kategorileri",
      heading: "Ürünlerimiz",
      viewAllText: "Tüm Ürünleri Gör",
    },
  },
  {
    section: "home.news",
    label: "Home News Header",
    title: "Güncel Haberler",
    content: "Haberler & Duyurular",
    metadata: {
      label: "Güncel Haberler",
      headingMain: "Haberler &",
      headingHighlight: "Duyurular",
      viewAllText: "Tüm Haberleri Gör",
    },
  },
  {
    section: "home.about",
    label: "Home About",
    title: "56 Yıllık Mükemmellik",
    content: "Kurumsal tanıtım alanı",
    imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=700&q=80",
    metadata: {
      label: "Kurumsal",
      headingMain: "56 Yıllık",
      headingHighlight: "Mükemmellik",
      paragraph1:
        "Vaden Original, 1968'den bu yana hava fren sistemleri ve otomotiv yedek parçaları üretiminde Türkiye'nin öncü markası olarak faaliyet göstermektedir.",
      paragraph2:
        "Konya'daki 105.000 m² kapalı üretim alanımızda, 1.500'den fazla çalışanımız ve 600'den fazla CNC makinemizle üretim yapıyoruz.",
      milestones: [
        { year: "1968", text: "Vaden Otomotiv kuruldu" },
        { year: "1985", text: "İhracata başlandı" },
        { year: "2000", text: "ISO 9001 sertifikası alındı" },
        { year: "2015", text: "Yeni Konya tesisi açıldı" },
        { year: "2024", text: "1 milyonuncu kompresör üretildi" },
      ],
      ctaText: "Daha Fazla Bilgi",
      ctaHref: "#kurumsal",
      imageAlt: "Vaden Üretim",
      quickStats: [
        { value: "56+", label: "Yıllık Deneyim" },
        { value: "110+", label: "İhracat Ülkesi" },
        { value: "1M+", label: "Üretilen Kompresör" },
        { value: "ISO 500", label: "Sanayi Kuruluşu" },
      ],
    },
  },
  {
    section: "home.stats",
    label: "Home Stats",
    title: "Küresel Liderlik",
    content: "Rakamlarla Vaden",
    metadata: {
      label: "Rakamlarla Vaden",
      heading: "Küresel Liderlik",
      stats: [
        { value: 56, suffix: "+", label: "Yıllık Deneyim", description: "Sektörde güvenilir bir isim" },
        { value: 110, suffix: "+", label: "İhracat Ülkesi", description: "5 kıtada küresel varlık" },
        { value: 500, suffix: "+", label: "Müşteri", description: "Dünya genelinde güvenilen marka" },
        { value: 1500, suffix: "+", label: "Çalışan", description: "Uzman ve deneyimli ekip" },
        { value: 105000, suffix: " m²", label: "Kapalı Üretim Alanı", description: "Modern üretim tesisleri" },
        { value: 600, suffix: "+", label: "CNC Makinesi", description: "İleri teknoloji makine parkı" },
      ],
    },
  },
  {
    section: "home.facilities",
    label: "Home Facilities",
    title: "Üretim Tesisleri",
    content: "Üretim gücü alanı",
    imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1920&q=80",
    metadata: {
      label: "Üretim Gücümüz",
      headingMain: "Üretim",
      headingHighlight: "Tesisleri",
      description:
        "56 yıldır en iyi bildiğimiz işi sürekli geliştirerek ve yenileyerek, üstün kalite standartlarıyla üretim yapıyoruz.",
      tabs: ["Konya Tesisi", "Bursa Tesisi"],
      ctaText: "Daha Fazla Bilgi",
      ctaHref: "#uretim",
      imageAlt: "Konya Üretim Tesisi",
      badgeValue: "56",
      badgeLine1: "Yıllık",
      badgeLine2: "Deneyim",
      stats: [
        { icon: "users", value: "1.200+", label: "Çalışan" },
        { icon: "zap", value: "6,5 mW", label: "Güneş Enerjisi" },
        { icon: "factory", value: "105K+", label: "m² Kapalı Alan" },
        { icon: "cpu", value: "600+", label: "CNC Makinesi" },
      ],
    },
  },
  {
    section: "home.awards",
    label: "Home Awards",
    title: "Ödüller & Başarılar",
    content: "Başarı kartları alanı",
    metadata: {
      label: "Başarılarımız",
      headingMain: "Ödüller &",
      headingHighlight: "Başarılar",
      awards: [
        {
          id: 1,
          icon: "trophy",
          rank: "401.",
          list: "ISO 500",
          title: "Türkiye'nin En Büyük 500 Sanayi Kuruluşu Arasındayız!",
          description: "ISO 500-2024 araştırmasında önemli bir yükseliş kaydettik.",
          href: "#",
        },
        {
          id: 2,
          icon: "trendingUp",
          rank: "365.",
          list: "TİM 1000",
          title: "Türkiye İhracatçılar Listesinde 365. Sıradayız!",
          description: "Türkiye İhracatçılar Meclisi listesinde 365. sıraya yükseldik.",
          href: "#",
        },
        {
          id: 3,
          icon: "award",
          rank: "85.",
          list: "AR-GE 500",
          title: "Ar-Ge 500 Listesinde 85. Sıradayız!",
          description: "2024 Yılında En Fazla Ar-Ge Harcaması Yapan 500 Şirket araştırmasında 85. sıradayız.",
          href: "#",
        },
      ],
      tabs: ["ISO 500", "TİM 1000", "AR-GE 500"],
      readMoreText: "Devamını Oku",
    },
  },
  {
    section: "home.rd",
    label: "Home R&D",
    title: "İnovasyonun Kalbi: Ar-Ge",
    content: "Ar-Ge ve inovasyon alanı",
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    metadata: {
      label: "Araştırma & Geliştirme",
      headingMain: "İnovasyonun",
      headingHighlight: "Kalbi: Ar-Ge",
      description:
        "Geleceği şekillendiren yenilikçi çözümler ve son teknolojilerle sektörü ilerleten Ar-Ge çalışmalarımız.",
      imageAlt: "Ar-Ge Departmanı",
      badgeRank: "85.",
      badgeTitle: "Ar-Ge 500 Listesi",
      badgeDescription: "Türkiye'nin En Fazla Ar-Ge Harcaması Yapan Şirketleri",
      ctaText: "Ar-Ge Departmanı",
      ctaHref: "#arge",
      features: [
        {
          icon: "lightbulb",
          title: "İnovasyon Merkezi",
          description: "Yenilikçi çözümler ve son teknolojilerle sektörü ilerleten Ar-Ge çalışmaları",
        },
        {
          icon: "flask",
          title: "Test Laboratuvarları",
          description: "En yüksek kalite ve güvenilirlik için gelişmiş test altyapısı",
        },
        {
          icon: "cpu",
          title: "Dijital Mühendislik",
          description: "CAD/CAM ve simülasyon teknolojileriyle ürün geliştirme süreçleri",
        },
        {
          icon: "shield",
          title: "Kalite Güvencesi",
          description: "Uluslararası standartlara uygun üretim ve kalite kontrol",
        },
      ],
    },
  },
  {
    section: "home.sustainability",
    label: "Home Sustainability",
    title: "Sürdürülebilir Üretim",
    content: "Sürdürülebilirlik metinleri",
    metadata: {
      label: "Yeşil Gelecek",
      headingMain: "Sürdürülebilir",
      headingHighlight: "Üretim",
      items: [
        {
          icon: "sun",
          title: "Güneş Enerjisi",
          value: "6,5 mW",
          description: "Çatı üzerindeki güneş panellerimizle 6,5 megawatt temiz enerji üretiyoruz.",
        },
        {
          icon: "leaf",
          title: "Karbon Azaltımı",
          value: "%30",
          description: "Son 5 yılda karbon ayak izimizi %30 oranında azalttık.",
        },
        {
          icon: "recycle",
          title: "Geri Dönüşüm",
          value: "%95",
          description: "Üretim atıklarımızın %95'ini geri dönüştürüyoruz veya yeniden kullanıyoruz.",
        },
        {
          icon: "wind",
          title: "Temiz Üretim",
          value: "ISO 14001",
          description: "Çevre yönetim sistemimiz ISO 14001 standardıyla sertifikalandırılmıştır.",
        },
      ],
    },
  },
  {
    section: "home.global",
    label: "Home Global",
    title: "Dünyaya Liderlik Ediyoruz",
    content: "Küresel varlık alanı",
    imageUrl: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1920&q=80",
    metadata: {
      label: "Küresel Varlık",
      headingMain: "Dünyaya",
      headingHighlight: "Liderlik Ediyoruz",
      description:
        "110'dan fazla ülkeye ihracat yaparak, 5 kıtada faaliyet göstererek, 500'den fazla müşteriyle hizmet vererek bir başarı hikayesi yazıyoruz.",
      mapAlt: "Küresel İhracat Ağı",
      stats: [
        {
          icon: "mapPin",
          value: "110+",
          label: "İhracat Ülkesi",
          description: "110'dan fazla ülkeye uzanan ihracat ağımızla kalite ve güven taşıyoruz.",
        },
        {
          icon: "globe",
          value: "5",
          label: "Kıta",
          description: "5 kıtada mevcut küresel ağımızla dünya standartlarında hizmet veriyoruz.",
        },
        {
          icon: "languages",
          value: "9",
          label: "Dil",
          description: "9 farklı dilde iletişim kurarak küresel ortaklarımızla işbirliği sağlıyoruz.",
        },
        {
          icon: "users",
          value: "500+",
          label: "Müşteri",
          description: "Müşterilerimizle güçlü ortaklıklar kuruyoruz.",
        },
        {
          icon: "trendingUp",
          value: "İlk 500",
          label: "İhracatçı",
          description: "Türkiye'nin ilk 500 ihracatçısı arasında yer alıyoruz.",
        },
      ],
    },
  },
  {
    section: "home.contact",
    label: "Home Contact",
    title: "İletişim",
    content: "İletişim formu ve bilgi kartları",
    metadata: {
      label: "Bize Ulaşın",
      heading: "İletişim",
      successMessage: "Mesajınız alındı! En kısa sürede size dönüş yapacağız.",
      contactInfo: [
        {
          icon: "mapPin",
          title: "Adres",
          lines: ["Vaden Otomotiv San. Tic. A.Ş.", "Konya Organize Sanayi Bölgesi", "Konya, Türkiye"],
        },
        {
          icon: "phone",
          title: "Telefon",
          lines: ["444 9 184", "+90 332 239 00 00"],
        },
        {
          icon: "mail",
          title: "E-posta",
          lines: ["info@vaden.com.tr", "export@vaden.com.tr"],
        },
        {
          icon: "clock",
          title: "Çalışma Saatleri",
          lines: ["Pazartesi - Cuma: 08:00 - 17:30", "Cumartesi: 08:00 - 13:00"],
        },
      ],
      labels: {
        name: "Ad Soyad *",
        email: "E-posta *",
        phone: "Telefon",
        subject: "Konu *",
        message: "Mesaj *",
        submit: "Mesaj Gönder",
      },
      placeholders: {
        name: "Adınız ve soyadınız",
        email: "E-posta adresiniz",
        phone: "Telefon numaranız",
        subject: "Mesajınızın konusu",
        message: "Mesajınızı buraya yazın...",
      },
    },
  },
  {
    section: "home.video",
    label: "Home Video",
    title: "Tanıtım Filmimiz",
    content: "Video alanı metinleri",
    imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1920&q=80",
    metadata: {
      kicker: "Vaden Original Fabrika Tanıtım Filmi",
      headingMain: "Tanıtım",
      headingHighlight: "Filmimizi İzleyin",
      imageAlt: "Vaden Fabrika Tanıtım Filmi",
      videoTitle: "Vaden Original Tanıtım Filmi",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1",
    },
  },
  {
    section: "pages.productDetail",
    label: "Ürün Detay Sayfası",
    title: "Ürün Detay Metinleri",
    content: "Ürün detay sayfası sabit etiket ve CTA metinleri",
    metadata: {
      notFoundTitle: "Ürün Bulunamadı",
      notFoundDescription: "Aradığınız ürün mevcut değil.",
      backToHomeText: "Ana Sayfaya Dön",
      breadcrumbHome: "Ana Sayfa",
      breadcrumbProducts: "Ürünler",
      featuresTitle: "Özellikler",
      downloadCatalogText: "Katalog İndir",
      shareText: "Paylaş",
      contactTitle: "Sorularınız mı var?",
      contactPhone: "444 9 184",
      contactEmail: "info@vaden.com.tr",
      specsTitle: "Teknik Özellikler",
      oemCodesTitle: "OEM Kodları",
      applicationsTitle: "Uygulamalar",
      certificationsTitle: "Sertifikasyonlar",
      relatedProductsTitle: "İlgili Ürünler",
      catalogDownloadToast: "Katalog indirme başlatıldı!",
      linkCopiedToast: "Bağlantı kopyalandı!",
    },
  },
  {
    section: "pages.searchResults",
    label: "Arama Sonuçları Sayfası",
    title: "Arama Sayfası Metinleri",
    content: "Arama sonuç ekranı başlık ve filtre etiketleri",
    metadata: {
      breadcrumbHome: "Ana Sayfa",
      breadcrumbCurrent: "Arama Sonuçları",
      pageTitle: "Arama Sonuçları",
      queryResultPrefix: "\"{query}\" için",
      queryResultSuffix: "ürün bulundu",
      noResultsTitle: "Sonuç Bulunamadı",
      noResultsPrefix: "\"{query}\" için eşleşen ürün yok. Lütfen arama terimini kontrol edin veya",
      noResultsCtaInline: "tüm ürünleri görün",
      noResultsSuffix: ".",
      noResultsBackHome: "Ana Sayfaya Dön",
      filtersTitle: "Filtreler",
      categoryTitle: "Kategori",
      allCategoriesText: "Tümü",
      sortTitle: "Sıralama",
      sortRelevance: "İlgililik",
      sortName: "Ad (A-Z)",
      oemMatchLabel: "OEM Kodu Eşleşmesi:",
      oemCodesLabel: "OEM Kodları:",
      moreSuffix: "daha",
      detailLinkText: "Detayları Gör",
    },
  },
  {
    section: "pages.corporate",
    label: "Kurumsal Sayfası",
    title: "Kurumsal Bilgiler",
    content: "Kurumsal sayfa metin ve tab içerikleri",
    metadata: {
      pageTitle: "Kurumsal | Vaden Original - Ağır Vasıta Yedek Parçaları",
      metaDescription:
        "1968'den bugüne Vaden Original'in başarı hikayesi, yönetim kurulu ve kalite sertifikalarımız.",
      metaKeywords:
        "vaden kurumsal, havalı fren sistemleri, ağır vasıta yedek parça, ISO 9001, IATF 16949",
      heroLabel: "Kurumsal",
      heroHeadingMain: "Kurumsal",
      heroHeadingHighlight: "Bilgiler",
      heroDescription: "56 yıllık deneyim, inovasyon ve kalite taahhüdümüzle sektöre değer katıyoruz.",
      tabs: [
        { id: "about", label: "Hakkımızda", title: "Hakkımızda" },
        { id: "history", label: "Tarihçe", title: "Tarihçe" },
        { id: "board", label: "Yönetim Kurulu", title: "Yönetim Kurulu" },
        { id: "certifications", label: "Sertifikalar", title: "Sertifikalar" },
      ],
      aboutParagraphs: [
        "Vaden Original, 1968'den bu yana hava fren sistemleri ve otomotiv yedek parçaları üretiminde Türkiye'nin öncü markasıdır.",
        "Konya'daki 105.000 m² kapalı üretim alanımızda, 1.500'den fazla çalışanımız ve 600'den fazla CNC makinemizle üretim yapıyoruz.",
        "Müşteri odaklılık, gizlilik ve güvenlik, iş etiği ve kurumsal sorumluluğa verdiğimiz önem iş yapış biçimimizin temelidir.",
      ],
      milestones: [
        { year: "1968", text: "Vaden Otomotiv kuruldu - Yıldız Enjektör ve Rekor Pulları adıyla" },
        { year: "1985", text: "İhracata başlandı" },
        { year: "2000", text: "ISO 9001 sertifikası alındı" },
        { year: "2007", text: "VADEN ORIGINAL markası hayata geçirildi" },
        { year: "2015", text: "Yeni Konya tesisi açıldı" },
        { year: "2018", text: "Türkiye'nin ilk 1000 ihracatçısı ve üretici firması arasına girdi" },
        { year: "2021", text: "İstanbul'da depo ve showroom açıldı, Turquality Programı'na dahil olundu" },
        { year: "2022", text: "Bursa AR-GE ve kauçuk fabrikası devreye alındı" },
        { year: "2024", text: "1 milyonuncu kompresör üretildi" },
        { year: "2025", text: "Unvan Vaden Otomotiv Sanayi ve Ticaret A.Ş. olarak değiştirildi" },
      ],
      boardMembers: [
        { name: "Yönetim Kurulu Başkanı", title: "Başkan" },
        { name: "Genel Müdür", title: "Genel Müdür" },
        { name: "Mali İşler Müdürü", title: "Mali İşler" },
        { name: "Üretim Müdürü", title: "Üretim" },
      ],
      certifications: [
        { name: "ISO 9001:2015", description: "Kalite Yönetim Sistemi", alt: "ISO 9001 Kalite Yönetim Sistemi Sertifikası" },
        { name: "IATF 16949:2016", description: "Otomotiv Kalite Yönetim Sistemi", alt: "IATF 16949 Otomotiv Kalite Yönetim Sistemi Sertifikası" },
        { name: "ISO 14001", description: "Çevre Yönetim Sistemi", alt: "ISO 14001 Çevre Yönetim Sistemi Sertifikası" },
        { name: "ISO 45001", description: "İş Sağlığı ve Güvenliği Yönetim Sistemi", alt: "ISO 45001 İş Sağlığı ve Güvenliği Yönetim Sistemi Sertifikası" },
      ],
    },
  },
  {
    section: "pages.career",
    label: "Kariyer Sayfası",
    title: "Kariyer Fırsatları",
    content: "Kariyer sayfası içerikleri",
    metadata: {
      pageTitle: "Kariyer | Vaden Otomotiv İş İlanları",
      metaDescription:
        "Vaden Otomotiv'de kariyerinize yön verin. Açık pozisyonları inceleyin ve ekibimize katılın.",
      metaKeywords: "vaden kariyer, otomotiv iş ilanları, Konya iş, Bursa iş",
      heroLabel: "İnsan Kaynakları",
      heroHeadingMain: "Kariyer",
      heroHeadingHighlight: "Fırsatları",
      heroDescription:
        "Vaden Otomotiv'de kariyerinizi geliştirin. Dinamik bir ekibin parçası olun ve sektörün geleceğini şekillendirin.",
      benefitsTitle: "Neden Vaden'de Çalışmalısınız?",
      jobsTitle: "Açık Pozisyonlar",
      benefits: [
        { icon: "💼", title: "Rekabetçi Maaş", description: "Sektör standartlarının üzerinde maaş ve yan haklar" },
        { icon: "🏥", title: "Sağlık Sigortası", description: "Kapsamlı sağlık ve hayat sigortası" },
        { icon: "📚", title: "Eğitim Programları", description: "Sürekli eğitim ve profesyonel gelişim fırsatları" },
        { icon: "🎯", title: "Kariyer Gelişimi", description: "Açık kariyer yolları ve ilerleme imkanları" },
        { icon: "⚖️", title: "İş-Yaşam Dengesi", description: "Esnek çalışma saatleri ve izin politikaları" },
        { icon: "🌱", title: "Sosyal Sorumluluk", description: "Sosyal ve çevresel projelere katılım" },
      ],
      jobs: [
        {
          id: 1,
          title: "CNC Operatörü",
          department: "Üretim",
          location: "Konya",
          type: "Tam Zamanlı",
          description: "Modern CNC makineleri ile çalışacak deneyimli operatör aranmaktadır.",
        },
        {
          id: 2,
          title: "Kalite Kontrol Mühendisi",
          department: "Kalite",
          location: "Konya",
          type: "Tam Zamanlı",
          description: "ISO standartlarına uygun kalite kontrol ve ürün testleri yapacak mühendis.",
        },
        {
          id: 3,
          title: "Ar-Ge Mühendisi",
          department: "Ar-Ge",
          location: "Bursa",
          type: "Tam Zamanlı",
          description: "Ürün geliştirme ve inovasyon projelerinde çalışacak mühendis aranmaktadır.",
        },
        {
          id: 4,
          title: "Satış Temsilcisi",
          department: "Satış",
          location: "İstanbul",
          type: "Tam Zamanlı",
          description: "Kurumsal müşterilerle ilişkileri yönetecek ve satış hedeflerini gerçekleştirecek temsilci.",
        },
      ],
      ctaTitle: "Sizin İçin Uygun Pozisyon Yok mu?",
      ctaDescription:
        "CV'nizi gönderin ve gelecekteki fırsatlar hakkında haberdar olun. Vaden Otomotiv'de yetenekli profesyonelleri arıyoruz.",
      ctaEmail: "insan-kaynakları@vaden.com.tr",
      ctaButtonText: "CV Gönder",
    },
  },
  {
    section: "pages.policies",
    label: "Politikalar Sayfası",
    title: "Politikalar & Şartlar",
    content: "Yasal politika içerikleri",
    metadata: {
      pageTitle: "Yasal Politikalar | Vaden Original KVKK ve Gizlilik",
      metaDescription:
        "Vaden Otomotiv Gizlilik Politikası, KVKK Aydınlatma Metni ve Çerez Politikası hakkında bilgiler.",
      metaKeywords: "gizlilik politikası, KVKK, çerez politikası, veri güvenliği, kişisel veriler",
      heroLabel: "Yasal",
      heroHeadingMain: "Politikalar &",
      heroHeadingHighlight: "Şartlar",
      heroDescription:
        "Vaden Otomotiv web sitesini kullanırken uygulanacak politikaları ve yasal şartları öğrenin.",
      policies: [
        {
          id: "privacy",
          title: "Gizlilik Politikası",
          content:
            "<h3>1. Giriş</h3><p>Vaden Otomotiv San. Tic. A.Ş. (\"Şirket\"), web sitesi ziyaretçilerinin kişisel verilerini korumaya önem vermektedir.</p><h3>2. Toplanan Bilgiler</h3><ul><li>Ad, soyad ve iletişim bilgileri</li><li>E-posta adresi</li><li>Telefon numarası</li></ul>",
        },
        {
          id: "kvkk",
          title: "KVKK Aydınlatma Metni",
          content:
            "<h3>Kişisel Verilerin Korunması Kanunu Aydınlatma Metni</h3><h3>1. Veri Sorumlusu</h3><p>Vaden Otomotiv San. Tic. A.Ş., Konya Organize Sanayi Bölgesi, Konya, Türkiye</p><h3>2. Kişisel Verilerin İşlenme Amaçları</h3><ul><li>Müşteri hizmetleri sağlamak</li><li>Ürün ve hizmetler hakkında bilgi vermek</li></ul>",
        },
        {
          id: "cookies",
          title: "Çerez Politikası",
          content:
            "<h3>1. Çerezler Nedir?</h3><p>Çerezler, web sitesi ziyaretçilerinin tarayıcılarında saklanan küçük metin dosyalarıdır.</p><h3>2. Kullandığımız Çerez Türleri</h3><ul><li><strong>Gerekli Çerezler:</strong> Web sitesinin düzgün çalışması için gereklidir</li><li><strong>Analitik Çerezler:</strong> Web sitesi ziyaretçi davranışlarını analiz etmek için kullanılır</li></ul>",
        },
      ],
      contactTitle: "Sorularınız mı var?",
      contactDescription:
        "Politikalar hakkında herhangi bir sorunuz varsa, lütfen bizimle iletişime geçin.",
      contactButtonText: "İletişim Sayfasına Git",
      contactButtonHref: "#iletisim",
    },
  },
];

export const PAGE_CONTENT_TEMPLATE_MAP: Record<string, PageContentTemplate> =
  PAGE_CONTENT_TEMPLATES.reduce<Record<string, PageContentTemplate>>((acc, template) => {
    acc[template.section] = template;
    return acc;
  }, {});
